/**
 * AUTO-GENERATED by scripts/generate-voiceover.ts — do not edit by hand.
 *
 * Maps each scene's audio file id (`v${chapter}-s${NN}`) to its actual
 * duration in seconds, measured from the ElevenLabs alignment response.
 * Chapter.tsx reads this to set frame-accurate scene durations.
 */

export const audioDurations: Record<string, number> = {
  "v1-s01": 16.811,
  "v1-s02": 20.341,
  "v1-s03": 23.545,
  "v1-s04": 48.437,
  "v1-s05": 44.768,
};

export const hasAudio = (chapter: number, sceneId: number): boolean =>
  `v${chapter}-s${String(sceneId).padStart(2, "0")}` in audioDurations;

export const audioDuration = (
  chapter: number,
  sceneId: number,
): number | undefined =>
  audioDurations[`v${chapter}-s${String(sceneId).padStart(2, "0")}`];
