export const STATES = [
  'pending',
  'running',
  'paused',
  'completed',
  'failed',
  'interrupted',
  'cancelled',
  'halted',
  'setup_failed',
  'unrecoverable',
  'planning',
  'integration_testing',
  'integration_failed',
  'blocked',
];

const ACTION_MATRIX = {
  stop: { running: true, planning: true, integration_testing: true },
  pause: { running: true, planning: true, integration_testing: true },
  resume: {
    paused: true,
    failed: true,
    interrupted: true,
    halted: true,
    integration_failed: true,
    blocked: true,
  },
  cancel: {
    pending: true,
    running: true,
    paused: true,
    failed: true,
    interrupted: true,
    halted: true,
    setup_failed: true,
    integration_failed: true,
    blocked: true,
  },
  archive: {
    paused: true,
    completed: true,
    failed: true,
    interrupted: true,
    cancelled: true,
    halted: true,
    setup_failed: true,
    unrecoverable: true,
    integration_failed: true,
  },
  unarchive: {
    completed: true,
    failed: true,
    interrupted: true,
    cancelled: true,
  },
  delete: {
    pending: true,
    paused: true,
    completed: true,
    failed: true,
    interrupted: true,
    cancelled: true,
    halted: true,
    setup_failed: true,
    unrecoverable: true,
    integration_failed: true,
    blocked: true,
  },
  learn: {
    paused: true,
    completed: true,
    failed: true,
    interrupted: true,
    cancelled: true,
    halted: true,
    integration_failed: true,
    blocked: true,
  },
};

export function actionAllowed(action, status) {
  return Boolean(ACTION_MATRIX[action]?.[status]);
}
